### ISSUE TITLE
segmentation fault after AssertError in execSQL

### ISSUE THREAD

**Issue by Extrawurst** [mysql-d/mysql-native#34] opened 2014-03-29 16:43 UTC
all of a sudden this excpetion appeared in my log. the server is doing a lot of SQL querys and does them perfectly fine for months with  no memory corruption what so ever

```
core.exception.AssertError@../../../../.dub/packages/vibe-d-0.7.19-rc.2/source/vibe/core/drivers/libevent2_tcp.d(344): Acquiring reader of already owned connection.
----------------
./s4server(_d_assert_msg+0x45) [0x7d178d]
./s4server(void vibe.core.drivers.libevent2_tcp.Libevent2TCPConnection.acquireReader()+0x80) [0x708160]
./s4server(void vibe.core.drivers.libevent2_tcp.Libevent2TCPConnection.read(ubyte[])+0x7b) [0x7078c3]
./s4server(void mysql.connection.MySQLSocketVibeD.read(ubyte[])+0x76) [0x6c3c02]
./s4server(ubyte[] mysql.connection.Connection.getPacket()+0x87) [0x6c4127]
./s4server(bool mysql.connection.Command.execSQL(out ulong)+0x87) [0x6cbbd3]
./s4server(mysql.connection.ResultSet mysql.connection.Command.execSQLResult(mysql.connection.ColumnSpecialization[])+0x86) [0x6cbdc2]
[...]
```

after that on the issuing mysql connection i called `close` anyway.

then one or more but not many ^^ requests later an otherwiser perfectly fine working query failed with:

```
mysql.connection.MySQLProtocolException@../../../../.dub/packages/mysql-native-master/source/mysql/connection.d(2153): Server packet out of order
```

then the server crashed with a segmentation fault -.-

**Comment by Abscissa** [comment] 2016-04-14 17:43
Is this still an issue? I'm wondering if the fix for #22 and/or improvements in Vibe.d may have fixed this.

**Comment by Skrupellos** [comment] 2016-06-06 01:35
@Abscissa I guess the problem still exists.
```
Task terminated with unhandled exception: Acquiring reader of already owned connection.
Full error: core.exception.AssertError@/home/skrupellos/.dub/packages/vibe-d-0.7.28/source/vibe/core/drivers/libevent2_tcp.d(412): Acquiring reader of already owned connection.
----------------
??:? _d_assert_msg [0xf6f8f0be]
/home/skrupellos/.dub/packages/vibe-d-0.7.28/source/vibe/core/drivers/libevent2_tcp.d:412 void vibe.core.drivers.libevent2_tcp.Libevent2TCPConnection.checkReader() [0x77c063]
/home/skrupellos/.dub/packages/vibe-d-0.7.28/source/vibe/core/drivers/libevent2_tcp.d:413 void vibe.core.drivers.libevent2_tcp.Libevent2TCPConnection.acquireReader() [0x77c081]
/home/skrupellos/.dub/packages/vibe-d-0.7.28/source/vibe/core/drivers/libevent2_tcp.d:277 void vibe.core.drivers.libevent2_tcp.Libevent2TCPConnection.read(ubyte[]) [0x77b628]
/home/skrupellos/.dub/packages/mysql-native-0.1.4/source/mysql/common.d:165 void mysql.common.MySQLSocketVibeD.read(ubyte[]) [0x747cc1]
/home/skrupellos/.dub/packages/mysql-native-0.1.4/source/mysql/connection.d:118 ubyte[] mysql.connection.Connection.getPacket() [0x736938]
/home/skrupellos/.dub/packages/mysql-native-0.1.4/source/mysql/protocol/commands.d:888 bool mysql.protocol.commands.Command.execPrepared(out ulong) [0x73f993]
```

**Comment by Abscissa** [comment] 2017-03-01 20:42
If @s-ludwig is correct [about the cause](https://github.com/mysql-d/mysql-native/issues/34#issuecomment-39702079), then this *should* be fixed in mysql-native v1.0.0 as long as you're not using the deprecated Command struct anymore, and not stashing a Prepared somewhere and using it across fibers (which you shouldn't be doing anyway - hmm, I should update its docs to reflect that).

Can anyone verify that this appears to have gone away in mysql-native v1.0.0 when all use of the deprecated Command struct is eliminated from your codebase (and no Prepared is stored and used across fibers)?

**Comment by Abscissa** [comment] 2018-02-09 12:01
The original error message makes it clear the problem stems from *something* using a connection that it doesn't rightfully have a lock for. As of v2.0.0, mysql-native no longer has *anything* that maintains a reference to a Connection. The library now operates *purely* on connections that were passed in as parameters and no longer stores references to those connections, ever.

So this should be resolved now, and any remaining cases of "Acquiring reader of already owned connection" are unlikely to be due to mysql-native.

So I'd say it's safe to close this now. But if anyone does still get this and suspects mysql-native, please try to reduce it to a reproducible test case and either re-open this issue or file a new one.

**Closed by Abscissa** 2018-02-09 12:01 UTC
Labels: bug

**Comment by Abscissa** [comment] 2018-02-25 05:14
>As of v2.0.0, mysql-native no longer has anything that maintains a reference to a Connection. The library now operates purely on connections that were passed in as parameters and no longer stores references to those connections, ever.

I was wrong about this. Both `mysql.result.Row` and `mysql.result.ResultRange` still (need to) store a reference to the `Connection` that created them. Because of that, Row and ResultRange should never be used across vibe tasks. I'm not sure what mysql-native could to to prevent that, but fortunately, it's unlikely to happen by accident.

However, that scenario does NOT appear to be the same problem people have reported above, based on the provided stack traces.

Because of that, and because there's been no report of this issue's original problem occurring in over a year, I'm going to keep this ticket closed.

If anyone does encounter the "Acquiring reader of already owned connection" problem again, then:

1. Please be certain you're not using a Row or ResultRange across tasks/fibers.

2. Open a separate ticket, and please try if at all possible to provide a reduced test case. (Though I realize that isn't always easy.)

And naturally, if needing to avoid using Row/ResultRange across fibers/tasks turns out to be problematic, then I'm open to reasonable arguments, as well as suggestions on what to do (in a separate ticket, please).
