### ISSUE TITLE
Using mysql-native driver with an empty database

### ISSUE THREAD

**Issue by stonemaster** [mysql-d/mysql-native#81] opened 2016-09-21 14:11 UTC
I'd like to use the mysql-native driver with no database set per defaullt aka. just omitting setting `;db=bla` in the connection string. When I do this and try to get some data out of table of a specific database like:

``` sql
SELECT * FROM `bla`.`table1`
```

I'm hitting the following error:

```
mysql.protocol.packets.MySQLReceivedException@../../../.dub/packages/mysql-native-0.1.6/source/mysql/protocol/commands.d(719): MySQL error: Incorrect table name ''
```

It seems that there is some logic inside the driver which always assumes a database specifier to be set.

**Comment by Abscissa** [comment] 2018-01-14 22:59
I'm unable to reproduce this. I couldn't find anything in mysql-native that seemed suspect, either. Are you still getting this?

FWIW, the message `Incorrect table name ''` is an error that the server sent. Maybe the server version you were using had some issues with omitting a default db?

Which MySQL/MariaDB server, version and server OS was this on? Have you tried doing the same thing with a different db client?

**Comment by schveiguy** [comment] 2021-01-23 15:44
Closing, please reopen if you still have this problem, and post an example.

**Closed by schveiguy** 2021-01-23 15:44 UTC
Labels: can't reproduce / need info
