### ISSUE TITLE
execSQLSequence doesn't work with map

### ISSUE THREAD

**Issue by MartinNowak** [mysql-d/mysql-native#52] opened 2014-10-21 14:13 UTC
``` d
foreach (row; Command(mysql, "SELECT 1").execSQLSequence())
    writeln(row);
foreach (row; Command(mysql, "SELECT 1").execSQLSequence().map!(r => r))
    writeln(row);
```

I think this is some problem with `execSQLSequence` because map can handle input/forward ranges.

**Comment by schveiguy** [comment] 2016-07-25 22:26
Is this an issue related to the fact that you can't copy or move an ExecSequence? If you copy, then the dtor will close the connection. If you move, then ExecSequence has internal pointers back to the originating Command struct, which now may have been destroyed.

Hard to tell, because I can't tell if you are saying it doesn't compile or that it doesn't actually work.

I feel like this whole piece needs attention, probably should be in a RefCounted container (that's how I solved it in my project). See issue #75

**Comment by MartinNowak** [comment] 2016-08-08 09:47
No data, so I guess it's destroyed on copy.

**Comment by Abscissa** [comment] 2017-03-01 20:29
mysql-native is much more heavily unit-tested now, since this issue was filed, and there were a bunch of fixes along the way, so hopefully this *should* be good now.

Can you verify whether or not you're still getting the problem with mysql-native v1.0.0? The relevant commands have changed though. Instead of:

```Command(connection, "SELECT 1").execSQLSequence()```

The equivalent command is now:

```connection.query("SELECT 1")```

**Comment by Abscissa** [comment] 2018-02-13 08:46
execSQLSequence no longer exists, and its functionality has been replaced by `query().array`. Added a [test case](https://github.com/mysql-d/mysql-native/blob/cf64a294a92990d1602728007ebc8fb1e3c419c1/source/mysql/test/regression.d#L146) for this, and the equivalent modern code appears to work now, so closing,

**Closed by Abscissa** 2018-02-13 08:46 UTC
Labels: bug
