### ISSUE TITLE
v2.3.0 always selects vibe-d:core instead of vibe-core

### ISSUE THREAD

**Issue by schveiguy** [mysql-d/mysql-native#201] opened 2019-09-28 23:02 UTC
I had to comment out this line: https://github.com/mysql-d/mysql-native/commit/ec851956e579bab8d00b1ae89a5344a2babce2e3

Can we leave that commented out now, or is it absolutely needed?

**Comment by itkfm** [comment] 2019-09-30 08:05
> Deprecation: the vibe-d:core package is deprecated and will be removed in January 2020. Please update your code to depend on vibe-core instead.

**Comment by schveiguy** [comment] 2019-10-01 15:34
Yeah, that's the message that clued me in that it's not selecting the right core. But I didn't think to look at the date! Certainly, this needs to be fixed soon. Maybe a version 3 of mysql-native requires vibe-core and doesn't support vibe-d:core? @Abscissa any thoughts?

**Comment by Abscissa** [comment] 2019-10-01 16:17
Been out-of-the-loop awhile as my day job got absurdly busy over the summer, so I haven't had a chance to refresh my memory on this stuff yet (plus I just got a new computer I'm still setting up) Things have mostly calmed back down now, so I should be able to dive back in again soon...

What I can say right now is this: My only concerns with this change are:

1. making sure not to break OSX in the process (I *think* this is the issue that caused the offending line to be added in the first place: https://github.com/vibe-d/vibe.d/issues/2155 ). And:

2. not breaking TOO much backwards compatibility. (I'm fine with a v3 that deprecates some older versions of dmd/vibe if necessary, depending how much).

What we need first is a simple PR that removes the offending line so travis-ci can tell us exactly what the breakages are (if any). Then we can go from there and either fix/deprecate those broken configurations as appropriate.

**Comment by schveiguy** [comment] 2019-10-01 17:24
I'll make a simple removal PR and see what happens. I actually wanted to add a mechanism to clean up unused mysql connections, but I ran into this first (was developing using 2.2.1 which didn't have this issue).

**Comment by Kozzi11** [comment] 2019-10-08 21:00
I would say this is duplicate of #199

**Comment by Abscissa** [comment] 2019-10-27 17:07
Now fixed. Mysqln master is now fully switched from "vibe-d:core" to "vibe-core".

**Closed by Abscissa** 2019-10-27 17:07 UTC
